name: create issue on commit 
on: push
jobs:
  create_commit:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secret.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was auto created by git Actions workflow **${{ github.workflow }}**. \n\n"
            }'
